import globals from 'globals';
import js from '@eslint/js';
import mocha from 'eslint-plugin-mocha';
import pluginChaiFriendly from 'eslint-plugin-chai-friendly';
import cypress from 'eslint-plugin-cypress';
import stylistic from '@stylistic/eslint-plugin';

export default [
  js.configs.recommended,
  {
    name: 'General Linting',
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
        _PRODUCTION_: true,
        _DEVELOP_: true,
        _TEST_: true,
        _NOW_: true,
      },
      ecmaVersion: 2020,
      sourceType: 'module',
    },
    plugins: {
      '@stylistic': stylistic,
    },
    rules: {
      '@stylistic/array-bracket-spacing': ['error', 'never'],
      'arrow-body-style': 'off',
      '@stylistic/arrow-parens': [2, 'as-needed'],
      'block-scoped-var': 'error',
      '@stylistic/block-spacing': ['error', 'always'],
      '@stylistic/brace-style': 'error',
      '@stylistic/comma-dangle': ['error', 'always-multiline'],
      '@stylistic/comma-spacing': 'error',
      '@stylistic/comma-style': 'error',
      'complexity': ['error', 8],
      '@stylistic/computed-property-spacing': ['error', 'never'],
      'curly': ['error', 'multi-line'],
      '@stylistic/dot-location': ['error', 'property'],
      'dot-notation': 'error',
      'eqeqeq': ['error', 'allow-null'],
      'guard-for-in': 'error',
      '@stylistic/indent': ['error', 2, { 'SwitchCase': 1 }],
      '@stylistic/key-spacing': ['error'],
      '@stylistic/keyword-spacing': 'error',
      'no-alert': 'error',
      'no-bitwise': 'error',
      'no-caller': 'error',
      'no-case-declarations': 'error',
      'no-cond-assign': ['error', 'except-parens'],
      'no-console': 'warn',
      'no-const-assign': 'error',
      'no-debugger': 'warn',
      'no-div-regex': 'error',
      'no-duplicate-imports': 'error',
      'no-else-return': 'error',
      'no-empty': 'error',
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-irregular-whitespace': 'error',
      'no-iterator': 'error',
      'no-lone-blocks': 'error',
      'no-loop-func': 'error',
      '@stylistic/no-multiple-empty-lines': 'error',
      '@stylistic/no-multi-spaces': 'error',
      'no-multi-str': 'error',
      'no-new-wrappers': 'error',
      'no-proto': 'error',
      'no-return-assign': 'error',
      'no-script-url': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-spaced-func': 'error',
      'no-shadow': 'error',
      'no-undef': 'error',
      'no-undef-init': 'error',
      'no-unexpected-multiline': 'error',
      'no-unneeded-ternary': 'error',
      'no-unused-vars': ['error', { 'args': 'none' }],
      'no-useless-concat': 'error',
      'no-useless-escape': 'off',
      'no-var': 'error',
      '@stylistic/no-whitespace-before-property': 'error',
      'no-with': 'error',
      '@stylistic/object-curly-spacing': ['error', 'always'],
      'one-var': ['error', 'never'],
      '@stylistic/operator-linebreak': ['error', 'before', {
        'overrides': {
          '?': 'after',
          ':': 'after',
        },
      }],
      '@stylistic/padded-blocks': ['error', 'never'],
      'prefer-const': 'error',
      'prefer-template': 'error',
      '@stylistic/quotes': ['error', 'single'],
      '@stylistic/quote-props': ['error', 'consistent'],
      'radix': ['error', 'always'],
      '@stylistic/semi': ['error', 'always'],
      '@stylistic/semi-spacing': ['error', {
        'before': false,
        'after': true,
      }],
      '@stylistic/space-before-blocks': 'error',
      '@stylistic/space-before-function-paren': ['error', 'never'],
      '@stylistic/space-in-parens': ['error', 'never'],
      '@stylistic/spaced-comment': ['error', 'always'],
      '@stylistic/space-infix-ops': 'error',
      'strict': 'off',
      '@stylistic/template-curly-spacing': ['error', 'always'],
      'valid-typeof': 'error',
      '@stylistic/wrap-iife': ['error', 'inside'],
    },
  },
  {
    name: 'Mocha Linting',
    files: ['test/**', '**/*.cy.js'],
    ...mocha.configs.recommended,
  },
  {
    name: 'Chai Linting',
    files: ['test/**', '**/*.cy.js'],
    ...pluginChaiFriendly.configs.recommendedFlat,
  },
  {
    name: 'Cypress Linting',
    files: ['test/**', '**/*.cy.js'],
    ...cypress.configs.recommended,
  },
  {
    name: 'Test Linting',
    files: ['test/**', '**/*.cy.js'],
    languageOptions: {
      globals: {
        ...globals.chai,
        ...cypress.configs.globals.languageOptions.globals,
      },
      ecmaVersion: 2020,
      sourceType: 'module',
    },
    rules: {
      'cypress/no-unnecessary-waiting': 'off',
      'cypress/unsafe-to-chain-command': 'off',
      'mocha/no-setup-in-describe': 'off',
      'no-console': 'warn',
      'no-debugger': 'warn',
    },
  },
];
