// Clean ES module wrapper for Five9 CRM SDK
// Auto-generated by update-sdk.js
import './five9.crm.sdk.js';

// The SDK attaches itself to window.Five9 when imported
// We'll capture the values and clean up the global namespace

const Five9SDK = window.Five9?.CrmSdk;
const sdkVersion = window.crmSdkVersion;

// Clean up global namespace
delete window.Five9;
delete window.crmSdkVersion;

// Export the main SDK
export default Five9SDK;

// Export individual APIs for convenience
export const defineApi = Five9SDK?.defineApi;
export const interactionApi = Five9SDK?.interactionApi;
export const customComponentsApi = Five9SDK?.customComponentsApi;
export const crmApi = Five9SDK?.crmApi;
export const hookApi = Five9SDK?.hookApi;
export const customMethodsApi = Five9SDK?.customMethodsApi;
export const sfNativeApi = Five9SDK?.sfNativeApi;
export const applicationApi = Five9SDK?.applicationApi;

// Export error codes and status codes
export const ApiErrorCode = Five9SDK?.ApiErrorCode;
export const HookStatusCode = Five9SDK?.HookStatusCode;

// Export the SDK version
export const version = sdkVersion;
